# Import Required Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [13]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix,accuracy_score

### Reading of data:

In [2]:
DS=pd.read_csv("Website Phishing.csv")

In [3]:
DS.head


<bound method NDFrame.head of       SFH  popUpWidnow  SSLfinal_State  Request_URL  URL_of_Anchor  \
0       1           -1               1           -1             -1   
1      -1           -1              -1           -1             -1   
2       1           -1               0            0             -1   
3       1            0               1           -1             -1   
4      -1           -1               1           -1              0   
...   ...          ...             ...          ...            ...   
1348   -1           -1              -1           -1             -1   
1349   -1            0               1            0             -1   
1350   -1            0              -1           -1             -1   
1351    0            0               1            0              0   
1352    1            0               1            1              1   

      web_traffic  URL_Length  age_of_domain  having_IP_Address  Result  
0               1           1              1           

In [4]:
DS

SFH  popUpWidnow  SSLfinal_State  Request_URL  URL_of_Anchor  \
0       1           -1               1           -1             -1   
1      -1           -1              -1           -1             -1   
2       1           -1               0            0             -1   
3       1            0               1           -1             -1   
4      -1           -1               1           -1              0   
...   ...          ...             ...          ...            ...   
1348   -1           -1              -1           -1             -1   
1349   -1            0               1            0             -1   
1350   -1            0              -1           -1             -1   
1351    0            0               1            0              0   
1352    1            0               1            1              1   

      web_traffic  URL_Length  age_of_domain  having_IP_Address  Result  
0               1           1              1                  0       0  
1               0           1              1                  1       1  
2               0          -1              1                  0       1  
3               0           1              1                  0       0  
4               0          -1              1                  0       1  
...           ...         ...            ...                ...     ...  
1348           -1           0              1                  0       1  
1349            0           0              1                  0      -1  
1350            0          -1             -1                  0       1  
1351            0          -1              1                  0       1  
1352            0          -1             -1                  0      -1  

[1353 rows x 10 columns]

# Handling Null Values

In [5]:
DS.info()
DS.isnull().any() #no null value.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1353 entries, 0 to 1352
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   SFH                1353 non-null   int64
 1   popUpWidnow        1353 non-null   int64
 2   SSLfinal_State     1353 non-null   int64
 3   Request_URL        1353 non-null   int64
 4   URL_of_Anchor      1353 non-null   int64
 5   web_traffic        1353 non-null   int64
 6   URL_Length         1353 non-null   int64
 7   age_of_domain      1353 non-null   int64
 8   having_IP_Address  1353 non-null   int64
 9   Result             1353 non-null   int64
dtypes: int64(10)
memory usage: 105.8 KB


SFH                  False
popUpWidnow          False
SSLfinal_State       False
Request_URL          False
URL_of_Anchor        False
web_traffic          False
URL_Length           False
age_of_domain        False
having_IP_Address    False
Result               False
dtype: bool

# Splitting The Data

### Splitting data into independent and dependent variables


In [18]:
x=DS.iloc[:,1:31].values
y=DS.iloc[:,-1].values
print(x,y)

[[-1  1 -1 ...  1  0  0]
 [-1 -1 -1 ...  1  1  1]
 [-1  0  0 ...  1  0  1]
 ...
 [ 0 -1 -1 ... -1  0  1]
 [ 0  1  0 ...  1  0  1]
 [ 0  1  1 ... -1  0 -1]] [ 0  1  1 ...  1  1 -1]


### Splitting the data into train and test:

In [23]:
from sklearn.model_selection import train_test_split

In [26]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)